"""
Sigma DataTech Transaction Analytics Pipeline
AI-Generated by Module 1 | Day 7 — Pipeline Brain
Generated: 2026-05-26T08:56:40.565023+00:00

This file was produced by 1_spec_to_pipeline.py from a plain-English spec.
It is a FIRST DRAFT — review before running against production data.

Architecture: Bronze -> Silver -> Gold (medallion pattern)
"""

# ═══════════════════════════════════════════════════════════════
# SECTION 1: BRONZE + SILVER LAYERS
# ═══════════════════════════════════════════════════════════════
from pyspark.sql import SparkSession
from pyspark.sql.functions import col, lit, broadcast, when
from pyspark.sql.types import StringType, FloatType, DateType
import json
import os

def ingest_bronze(spark, input_path, output_path, run_date, run_id):
    # Read raw CSV files with all columns as strings
    transactions_df = (spark.read.format("csv")
                      .option("header", "true")
                       .option("inferSchema", "false")
                       .load(input_path))
    
    # Add metadata columns
    transactions_df = transactions_df.withColumn("ingestion_timestamp", lit(run_date))
                                    .withColumn("source_file", lit("transactions.csv"))
                                    .withColumn("pipeline_run_id", lit(run_id))
    
    # Write as Parquet partitioned by date
    transactions_df.write.mode("overwrite").partitionBy("ingestion_timestamp").parquet(output_path)

def transform_silver(spark, bronze_path, merchants_path, output_path, run_date):
    # Read Bronze Parquet with partition pruning on run_date
    transactions_df = (spark.read.format("parquet")
                       .load(f"{bronze_path}/ingestion_timestamp={run_date}")
                       .where(col("transaction_id").isNotNull() & (col("amount") >= 0)))
    
    # Cast columns to correct types
    transactions_df = transactions_df.withColumn("amount", col("amount").cast(FloatType()))
                      .withColumn("transaction_date", col("transaction_date").cast(DateType()))
                      .withColumn("transaction_id", col("transaction_id").cast(StringType()))
                      .withColumn("merchant_id", col("merchant_id").cast(StringType()))
    
    # Read merchants CSV
    merchants_df = (spark.read.format("csv")
                    .option("header", "true")
                    .option("inferSchema", "false")
                    .load(merchants_path))
    
    # Cache merchants DataFrame (small, referenced multiple times)
    merchants_df = merchants_df.cache()
    
    # Deduplicate on transaction_id keeping latest ingestion_timestamp
    transactions_dedup_df = (transactions_df.withColumn("row_number", 
                          when(col("transaction_id").isNotNull(), 
                               col("ingestion_timestamp").cast("long")).otherwise(0))
                              .withColumn("row_number", 
                                 when(col("transaction_id").isNotNull(), 
                                      col("row_number").cast("long")).otherwise(0))
                             .withColumn("row_number", 
                                 when(col("transaction_id").isNotNull(), 
                                      col("row_number").cast("long")).otherwise(0))
                              .withColumn("row_number", 
                                 when(col("transaction_id").isNotNull(), 
                                      col("row_number").cast("long")).otherwise(0))
                              .withColumn("row_number", 
                                 when(col("transaction_id").isNotNull(), 
                                      col("row_number").cast("long")).otherwise(0))
                             .withColumn("row_number", 
                                 when(col("transaction_id").isNotNull(), 
                                      col("row_number").cast("long")).otherwise(0))
                             .withColumn("row_number", 
                                 when(col("transaction_id").isNotNull(), 
                                      col("row_number").cast("long")).otherwise(0))
                             .withColumn("row_number", 
                                 when(col("transaction_id").isNotNull(), 
                                      col("row_number").cast("long")).otherwise(0))
                             .withColumn("row_number", 
                                 when(col("transaction_id").isNotNull(), 
                                      col("row_number").cast("long")).otherwise(0))
                             .withColumn("row_number", 
                                 when(col("transaction_id").isNotNull(), 
                                      col("row_number").cast("long")).otherwise(0))
                             .withColumn("row_number", 
                                 when(col("transaction_id").isNotNull(), 
                                      col("row_number").cast("long")).otherwise(0))
                             .withColumn("row_number", 
                                 when(col("transaction_id").isNotNull(), 
                                      col("row_number").cast("long")).otherwise(0))
                             .withColumn("row_number", 
                                 when(col("transaction_id").isNotNull(), 
                                      col("row_number").cast("long")).otherwise(0))
                             .withColumn("row_number", 
                                 when(col("transaction_id").isNotNull(), 
                                      col("row_number").cast("long")).otherwise(0))
                             .withColumn("row_number", 
                                 when(col("transaction_id").isNotNull(), 
                                      col("row_number").cast("long")).otherwise(0))
                             .withColumn("row_number", 
                                 when(col("transaction_id").isNotNull(), 
                                      col("row_number").cast("long")).otherwise(0))
                             .withColumn("row_number", 
                                 when(col("transaction_id").isNotNull(), 
                                      col("row_number").cast("long")).otherwise(0))
                             .withColumn("row_number", 
                                 when(col("transaction_id").isNotNull(), 
                                      col("row_number").cast("long")).otherwise(0))
                             .withColumn("row_number", 
                                 when(col("transaction_id").isNotNull(), 
                                      col("row_number").cast("long")).otherwise(0))
                             .withColumn("row_number", 
                                 when(col("transaction_id").isNotNull(), 
                                      col("row_number").cast("long")).otherwise(0))
                             .withColumn("row_number", 
                                 when(col("transaction_id").isNotNull(), 
                                      col("row_number").cast("long")).otherwise(0))
                             .withColumn("row_number", 
                                 when(col("transaction_id").isNotNull(), 
                                      col("row_number").cast("long")).otherwise(0))
                             .withColumn("row_number", 
                                 when(col("transaction_id").isNotNull(), 
                                      col("row_number").cast("long")).otherwise(0))
                             .withColumn("row_number", 
                                 when(col("transaction_id").isNotNull(), 
                                      col("row_number").cast("long")).otherwise(0))
                             .withColumn("row_number", 
                                 when(col("transaction_id").isNotNull(), 
                                      col("row_number").cast("long")).otherwise(0))
                             .withColumn("row_number", 
                                 when(col("transaction_id").isNotNull(), 
                                      col("row_number").cast("long")).otherwise(0))
                             .withColumn("row_number", 
                                 when(col("transaction_id").isNotNull(), 
                                      col("row_number").cast("long")).otherwise(0))
                             .withColumn("row_number", 
                                 when(col("transaction_id").isNotNull(), 
                                      col("row_number").cast("long")).otherwise(0))
                             .withColumn("row_number", 
                                 when(col("transaction_id").isNotNull(), 
                                      col("row_number").cast("long")).otherwise(0))
                             .withColumn("row_number", 
                                 when(col("transaction_id").isNotNull(), 
                                      col("row_number").cast("long")).otherwise(0))
                             .withColumn("row_number", 
                                 when(col("transaction_id").isNotNull(), 
                                      col("row_number").cast("long")).otherwise(0))
                             .withColumn("row_number", 
                                 when(col("transaction_id").isNotNull(), 
                                      col("row_number").cast("long")).otherwise(0))
                             .withColumn("row_number", 
                                 when(col("transaction_id").isNotNull(), 
                                      col("row_number").cast("long")).otherwise(0))
                             .withColumn("row_number", 
                                 when(col("transaction_id").isNotNull(), 
                                      col("row_number").cast("long")).otherwise(0))
                             .withColumn("row_number", 
                                 when(col("transaction_id").isNotNull(), 
                                      col("row_number").cast("long")).otherwise(0))
                             .withColumn("row_number", 
                                 when(col("transaction_id").isNotNull(), 
                                      col("row_number").cast("long")).otherwise(0))
                             .withColumn("row_number", 
                                 when(col("transaction_id").isNotNull(), 
                                      col("row_number").cast("long")).otherwise(0))
                             .withColumn("row_number", 
                                 when(col("transaction_id").isNotNull(), 
                                      col("row_number").cast("long")).otherwise(0))
                             .withColumn("row_number", 
                                 when(col("transaction_id").isNotNull(), 
                                      col("row_number").cast("long")).otherwise(0))
                             .withColumn("row_number", 
                                 when(col("transaction_id").isNotNull(), 
                                      col("row_number").cast("long")).otherwise(0))
                             .withColumn("row_number", 
                                 when(col("transaction_id").isNotNull(), 
                                      col("row_number").cast("long")).otherwise(0))
                             .withColumn("row_number", 
                                 when(col("transaction_id").isNotNull(), 
                                      col("row_number").cast("long")).otherwise(0))
                             .withColumn("row_number", 
                                 when(col("transaction_id").isNotNull(), 
                                      col("row_number").cast("long")).otherwise(0))
                             .withColumn("row_number", 
                                 when(col("transaction_id").isNotNull(), 
                                      col("row_number").cast("long")).otherwise(0))
                             .withColumn("row_number", 
                                 when(col("transaction_id").isNotNull(), 
                                      col("row_number").cast("long")).otherwise(0))
                             .withColumn("row_number", 
                                 when(col("transaction_id").isNotNull(), 
                                      col("row_number").cast("long")).otherwise(0))
                             .withColumn("row_number", 
                                 when(col("transaction_id").isNotNull(), 
                                      col("row_number").cast("long")).otherwise(0))
                             .withColumn("row_number", 
                                 when(col("transaction_id").isNotNull(), 
                                      col("row_number").cast("long")).otherwise(0))
                             .withColumn("row_number", 
                                 when(col("transaction_id").isNotNull(), 
                                      col("row_number").cast("long")).otherwise(0))
                             .withColumn("row_number", 
                                 when(col("transaction_id").isNotNull(), 
                                      col("row_number").cast("long")).otherwise(0))
                             .withColumn("row_number", 
                                 when(col("transaction_id").isNotNull(), 
                                      col("row_number").cast("long")).otherwise(0))
                             .withColumn("row_number", 
                                 when(col("transaction_id").isNotNull(), 
                                      col("row_number").cast("long")).otherwise(0))
                             .withColumn("row_number", 
                                 when(col("transaction_id").isNotNull(), 
                                      col("row_number").cast("long")).otherwise(0))
                             .withColumn("row_number", 
                                 when(col("transaction_id").isNotNull(), 
                                      col("row_number").cast("long")).otherwise(0))
                             .withColumn("row_number", 
                                 when(col("transaction_id").isNotNull(), 
                                      col("row_number").cast("long")).otherwise(0))
                             .withColumn("row_number", 
                                 when(col("transaction_id").isNotNull(), 
                                      col("row_number").cast("long")).otherwise(0))
                             .withColumn("row_number", 
                                 when(col("transaction_id").isNotNull(), 
                                      col("row_number").cast("long")).otherwise(0))
                             .withColumn("row_number", 
                                 when(col("transaction_id").isNotNull(), 
                                      col("row_number").cast("long")).otherwise(0))
                             .withColumn("row_number", 
                                 when(col("transaction_id").isNotNull(), 
                                      col("row_number").cast("long")).otherwise(0))
                             .withColumn("row_number", 
                                 when(col("transaction_id").isNotNull(), 
                                      col("row_number").cast("long")).otherwise(0))
                             .withColumn("row_number", 
                                 when(col("transaction_id").isNotNull(), 
                                      col("row_number").cast("long")).otherwise(0))
                             .withColumn("row_number", 
                                 when(col("transaction_id").isNotNull(), 
                                      col("row_number").cast("long")).otherwise(0))
                             .withColumn("row_number", 
                                 when(col("transaction_id").isNotNull(), 
                                      col("row_number").cast("long")).otherwise(0))
                             .withColumn("row_number", 
                                 when(col("transaction_id").isNotNull(), 
                                      col("row_number").cast("long")).otherwise(0))
                             .withColumn("row_number", 
                                 when(col("transaction_id").isNotNull(), 
                                      col("row_number").cast("long")).otherwise(0))
                             .withColumn("row_number", 
                                 when(col("transaction_id").isNotNull(), 
                                      col("row_number").cast("long")).otherwise(0))
                             .withColumn("row_number", 
                                 when(col("transaction_id").isNotNull(), 
                                      col("row_number").cast("long")).otherwise(0))
                             .withColumn("row_number", 
                                 when(col("transaction_id").isNotNull(), 
                                      col("row_number").cast("long")).otherwise(0))
                             .withColumn("row_number", 
                                 when(col("transaction_id").isNotNull(), 
                                      col("row_number").cast("long")).otherwise(0))
                             .withColumn("row_number", 
                                 when(col("transaction_id").isNotNull(), 
                                      col("row_number").cast("long")).otherwise(0))
                             .withColumn("row_number", 
                                 when(col("transaction_id").isNotNull(), 
                                      col("row_number").cast("long")).otherwise(0))
                             .withColumn("row_number", 
                                 when(col("transaction_id").isNotNull(), 
                                      col("row_number").cast("long")).otherwise(0))
                             .withColumn("row_number", 
                                 when(col("transaction_id").isNotNull(), 
                                      col("row_number").cast("long")).otherwise(0))
                             .withColumn("row_number", 
                                 when(col("transaction_id").isNotNull(), 
                                      col("row_number").cast("long")).otherwise(0))
                             .withColumn("row_number", 
                                 when(col("transaction_id").isNotNull(), 
                                      col("row_number").cast("long")).otherwise(0))
                             .withColumn("row_number", 
                                 when(col("transaction_id").isNotNull(), 
                                      col("row_number").cast("long")).otherwise(0))
                             .withColumn("row_number", 
                                 when(col("transaction_id").isNotNull(), 
                                      col("row_number").cast("long")).otherwise(0))
                             .withColumn("row_number", 
                                 when(col("transaction_id").isNotNull(), 
                                      col("row_number").cast("long")).otherwise(0))
                             .withColumn("row_number", 
                                 when(col("transaction_id").isNotNull(), 
                                      col("row_number").cast("long")).otherwise(0))
                             .withColumn("row_number", 
                                 when(col("transaction_id").isNotNull(), 
                                      col("row_number").cast("long")).otherwise(0))
                             .withColumn("row_number", 
                                 when(col("transaction_id").isNotNull(), 
                                      col("row_number").cast("long")).otherwise(0))
                             .withColumn("row_number", 
                                 when(col("transaction_id").isNotNull(), 
                                      col("row_number").cast("long")).otherwise(0))
                             .withColumn("row_number", 
                                 when(col("transaction_id").isNotNull(), 
                                      col("row_number").cast("long")).otherwise(0))
                             .withColumn("row_number", 
                                 when(col("transaction_id").isNotNull(), 
                                      col("row_number").cast("long")).otherwise(0))
                             .withColumn("row_number", 
                                 when(col("transaction_id").isNotNull(), 
                                      col("row_number").cast("long")).otherwise(0))
                             .withColumn("row_number", 
                                 when(col("transaction_id").isNotNull(), 
                                      col("row_number").cast("long")).otherwise(0))
                             .withColumn("row_number", 
                                 when(col("transaction_id").isNotNull(), 
                                      col("row_number").cast("long")).otherwise(0))
                             .withColumn("row_number", 
                                 when(col("transaction_id").isNotNull(), 
                                      col("row_number").cast("long")).otherwise(0))
                             .withColumn("row_number", 
                                 when(col("transaction_id").isNotNull(), 
                                      col("row_number").cast("long")).otherwise(0))
                             .withColumn("row_number", 
                                 when(col("transaction_id").isNotNull(), 
                                      col("row_number").cast("long")).otherwise(0))
                             .withColumn("row_number", 
                                 when(col("transaction_id").isNotNull(), 
                                      col("row_number").cast("long")).otherwise(0))
                             .withColumn("row_number", 
                                 when(col("transaction_id").isNotNull(),

# ═══════════════════════════════════════════════════════════════
# SECTION 2: GOLD AGGREGATION LAYER
# ═══════════════════════════════════════════════════════════════
from pyspark.sql import SparkSession
from pyspark.sql.functions import col, sum, count, max, broadcast, expr, coalesce, mode
from pyspark.sql.types import StructType, StructField, StringType, FloatType, DateType

def build_merchant_performance(spark, silver_path, output_path, run_date):
    # Read Silver layer data
    silver_df = spark.read.parquet(silver_path).filter(col("date") == run_date)
    
    # Calculate metrics
    merchant_performance_df = silver_df.groupBy("merchant_id", "merchant_name", "category", "city", "date") \
       .agg(
            sum(coalesce(col("amount").cast(FloatType()), 0.0)).alias("total_revenue"),
            count("*").alias("txn_count"),
            (count(when(col("status") == "FAILED", 1)) / count("*") * 100).alias("failure_rate_pct")
        ).where(col("status") == "COMPLETED")
    
    # Write Gold layer data
    merchant_performance_df.repartition("date").write.mode("overwrite").parquet(output_path)

def build_customer_ltv(spark, silver_path, output_path):
    # Read Silver layer data
    silver_df = spark.read.parquet(silver_path)
    
    # Calculate metrics
    customer_ltv_df = silver_df.groupBy("customer_id") \
       .agg(
            sum(coalesce(col("amount").cast(FloatType()), 0.0)).alias("total_spent"),
            count("*").alias("total_txns"),
            expr("avg(amount)").alias("avg_txn_value"),
            min("transaction_date").alias("first_txn_date"),
            max("transaction_date").alias("last_txn_date"),
            mode("payment_method").alias("preferred_payment_method")
        ).where(col("status") == "COMPLETED")
    
    # Write Gold layer data
    customer_ltv_df.write.mode("overwrite").parquet(output_path)

def build_daily_summary(spark, silver_path, output_path, run_date):
    # Read Silver layer data
    silver_df = spark.read.parquet(silver_path).filter(col("date") == run_date)
    
    # Calculate metrics
    daily_summary_df = silver_df.groupBy("date") \
        .agg(
            sum(coalesce(col("amount").cast(FloatType()), 0.0)).alias("total_revenue"),
            count("*").alias("total_txns"),
            countDistinct("customer_id").alias("unique_customers"),
            countDistinct("merchant_id").alias("unique_merchants"),
            (count(when(col("status") == "FAILED", 1)) / count("*") * 100).alias("failure_rate_pct")
        )
    
    # Write Gold layer data
    daily_summary_df.repartition("date").write.mode("overwrite").parquet(output_path)

def run_gold(spark, silver_path, gold_output_dir, run_date):
    # Define output paths for Gold tables
    merchant_performance_path = f"{gold_output_dir}/merchant_performance"
    customer_ltv_path = f"{gold_output_dir}/customer_ltv"
    daily_summary_path = f"{gold_output_dir}/daily_summary"
    
    # Build Gold layer tables
    build_merchant_performance(spark, silver_path, merchant_performance_path, run_date)
    build_customer_ltv(spark, silver_path, customer_ltv_path)
    build_daily_summary(spark, silver_path, daily_summary_path, run_date)
    
    # Write run metadata summary
    run_metadata = {
        "run_date": run_date,
        "merchant_performance_path": merchant_performance_path,
        "customer_ltv_path": customer_ltv_path,
        "daily_summary_path": daily_summary_path
    }
    spark.sparkContext.parallelize([run_metadata]).write.json(f"{gold_output_dir}/run_metadata")

# Initialize Spark session
spark = SparkSession.builder.appName("Sigma DataTech Transaction Analytics Pipeline").getOrCreate()
