"""
Sigma DataTech Transaction Analytics Pipeline
AI-Generated by Module 1 | Day 7 — Pipeline Brain
Generated: 2026-05-26T08:54:51.930312+00:00

This file was produced by 1_spec_to_pipeline.py from a plain-English spec.
It is a FIRST DRAFT — review before running against production data.

Architecture: Bronze -> Silver -> Gold (medallion pattern)
"""

# ═══════════════════════════════════════════════════════════════
# SECTION 1: BRONZE + SILVER LAYERS
# ═══════════════════════════════════════════════════════════════
from pyspark.sql import SparkSession
from pyspark.sql.functions import col, upper, lit, to_date, broadcast, expr
from pyspark.sql.types import StructType, StructField, StringType, TimestampType, IntegerType, FloatType, DateType
import sys

def ingest_bronze(spark, input_path, output_path, run_date, run_id):
    # Define schema for the bronze layer
    bronze_schema = StructType([
        StructField("transaction_id", StringType(), True),
        StructField("merchant_id", StringType(), True),
        StructField("txn_timestamp", StringType(), True),
        StructField("amount", StringType(), True),
        StructField("status", StringType(), True),
        StructField("currency", StringType(), True)
    ])
    
    # Read the input CSV with the defined schema
    bronze_df = spark.read.option("header", "true").schema(bronze_schema).csv(input_path)
    
    # Add metadata columns
    bronze_df = bronze_df.withColumn("_ingest_ts", lit(run_date)) \
                         .withColumn("_source_file", lit(input_path)) \
                        .withColumn("_batch_date", expr("to_date(_ingest_ts)")) \
                         .withColumn("_pipeline_run_id", lit(run_id))
    
    # Write the DataFrame to the output path partitioned by _batch_date
    bronze_df.write.mode("overwrite").partitionBy("_batch_date").parquet(output_path)

def transform_silver(spark, bronze_path, merchants_path, output_path, run_date):
    # Read the Bronze layer with partition pruning
    bronze_df = spark.read.parquet(bronze_path).where(col("_batch_date") == run_date)
    
    # Cast columns to the correct types
    silver_df = bronze_df.withColumn("txn_timestamp", col("txn_timestamp").cast(TimestampType())) \
                         .withColumn("amount", col("amount").cast(FloatType())) \
                        .withColumn("status", upper(col("status")).cast(StringType()))
    
    # Filter out invalid rows
    silver_df = silver_df.filter(
        (col("transaction_id").isNotNull()) &
        (col("merchant_id").isNotNull()) &
        (col("status").isin("SUCCESS", "FAILED")) &
        (col("amount") >= 0)
    )
    
    # Deduplicate based on transaction_id, keeping the latest record
    silver_df = silver_df.sortWithinPartitions("transaction_id", "_ingest_ts", ascending=False) \
                         .dropDuplicates(["transaction_id"]) \
                         .sort("transaction_id")
    
    # Read the merchants data and broadcast it for the join
    merchants_df = spark.read.parquet(merchants_path)
    merchants_df = broadcast(merchants_df)
    
    # Join with merchants and add quality_flag
    silver_df = silver_df.join(merchants_df, "merchant_id", "left") \
                        .withColumn("quality_flag", expr("CASE WHEN merchant_id IS NULL THEN 'UNMATCHED' ELSE 'CLEAN' END"))
    
    # Write the Silver layer partitioned by txn_date
    silver_df.write.mode("overwrite").partitionBy("txn_date").parquet(output_path)

def main():
    # Initialize Spark session
    spark = SparkSession.builder.appName("Merchant Risk Detection Pipeline").getOrCreate()
    
    # Define paths and dates
    input_path = "s3://path/to/bronze/landing/zone"
    bronze_output_path = "s3://path/to/bronze/storage"
    silver_output_path = "s3://path/to/silver/storage"
    merchants_path = "s3://path/to/merchants/data"
    run_date = "2023-04-01"
    run_id = "run_id_12345"
    
    # Ingest bronze layer
    ingest_bronze(spark, input_path, bronze_output_path, run_date, run_id)
    
    # Transform to silver layer
    transform_silver(spark, bronze_output_path, merchants_path, silver_output_path, run_date)

if __name__ == "__main__":
    main()


# ═══════════════════════════════════════════════════════════════
# SECTION 2: GOLD AGGREGATION LAYER
# ═══════════════════════════════════════════════════════════════
from pyspark.sql import SparkSession
from pyspark.sql.functions import col, broadcast, expr, sum, count, max, min, mode, to_date
from pyspark.sql.types import StructType, StructField, StringType, IntegerType, FloatType, TimestampType, DecimalType

def build_merchant_performance(spark, silver_path, output_path, run_date):
    # Read the Silver layer data
    silver_df = spark.read.parquet(silver_path).where(col("status").isin(["SUCCESS", "FAILED"]))
    
    # Perform the necessary aggregations
    merchant_performance_df = silver_df.groupBy("merchant_id", to_date("txn_timestamp").alias("date")) \
        .agg(
            sum(when(col("status") == "SUCCESS", col("amount")).otherwise(0)).alias("total_revenue"),
            count("*").alias("txn_count"),
            (count(when(col("status") == "FAILED", 1)) / count("*")).alias("failure_rate_pct")
        )
    
    # Write the merchant performance data to the output path
    merchant_performance_df.repartition("date").write.mode("overwrite").parquet(output_path)

def build_customer_ltv(spark, silver_path, output_path):
    # Read the Silver layer data
    silver_df = spark.read.parquet(silver_path).where(col("status") == "SUCCESS")
    
    # Perform the necessary aggregations
    customer_ltv_df = silver_df.groupBy("customer_id") \
       .agg(
            sum("amount").alias("total_spent"),
            count("*").alias("total_txns"),
            avg("amount").alias("avg_txn_value"),
            min("txn_timestamp").alias("first_txn_date"),
            max("txn_timestamp").alias("last_txn_date"),
            mode("payment_method").alias("preferred_payment_method")
        )
    
    # Write the customer LTV data to the output path
    customer_ltv_df.write.mode("overwrite").parquet(output_path)

def build_daily_summary(spark, silver_path, output_path, run_date):
    # Read the Silver layer data
    silver_df = spark.read.parquet(silver_path).where(col("status").isin(["SUCCESS", "FAILED"]))
    
    # Perform the necessary aggregations
    daily_summary_df = silver_df.groupBy(to_date("txn_timestamp").alias("date")) \
        .agg(
            sum(when(col("status") == "SUCCESS", col("amount"))).alias("total_revenue"),
            count("*").alias("total_txns"),
            count(distinct("customer_id")).alias("unique_customers"),
            count(distinct("merchant_id")).alias("unique_merchants"),
            (count(when(col("status") == "FAILED", 1)) / count("*") * 100).alias("failure_rate_pct")
        )
    
    # Write the daily summary data to the output path
    daily_summary_df.repartition("date").write.mode("overwrite").parquet(output_path)

def run_gold(spark, silver_path, gold_output_dir, run_date):
    # Define the output paths for each Gold table
    merchant_performance_output_path = f"{gold_output_dir}/merchant_performance"
    customer_ltv_output_path = f"{gold_output_dir}/customer_ltv"
    daily_summary_output_path = f"{gold_output_dir}/daily_summary"
    
    # Build the merchant performance table
    build_merchant_performance(spark, silver_path, merchant_performance_output_path, run_date)
    
    # Build the customer LTV table
    build_customer_ltv(spark, silver_path, customer_ltv_output_path)
    
    # Build the daily summary table
    build_daily_summary(spark, silver_path, daily_summary_output_path, run_date)
    
    # Write the run metadata to a JSON file
    run_metadata = {
        "run_date": run_date,
        "output_paths": {
            "merchant_performance": merchant_performance_output_path,
            "customer_ltv": customer_ltv_output_path,
            "daily_summary": daily_summary_output_path
        }
    }
    spark.sparkContext.parallelize([run_metadata]).write.json(f"{gold_output_dir}/run_metadata")

# Initialize Spark session
spark = SparkSession.builder.appName("GoldLayerPipeline").getOrCreate()
